services:
  app:
    build: https://github.com/Mnky313/my-yt.git
    container_name: my-yt
    working_dir: /app
    volumes:
     - YouTube:/app/data
    ports:
    - "3333:3000"
    command: npm start
    # network_mode: host
volumes:
  YouTube:
    external: true
