name: "Bug report"
description: Report errors or unexpected behavior
labels:
- bug
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/christian-fei/my-yt/issues) before filing a new one! Please also check the [contributor todo list](https://github.com/christian-fei/my-yt/issues/5) and ensure there isn't already an entry for your issue/improvement proposal.

- type: dropdown
  attributes:
    label: Installation method
    description: How do you run my-yt?
    multiple: false
    options:
      - docker
      - node.js
  validations:
    required: true

- type: input
  attributes:
    label: Bug Summary
    description: A brief description of the issue.
    placeholder: "e.g., 'App crashes when ...'"
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots and the application logs (check your terminal).
    placeholder: Having detailed steps helps us reproduce the bug. 
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false
